import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { CardActivitiesModule, CardAuthModule, CardMessagesModule, CardNotesModule, ChangeProfilePasswordFormModule, ContactStatusModule, ConversionCardModule, ConversionTickerModule, CreateAccountFormModule, FormPhotoModule, FormPopupModule, FormTextboxModule, LeadsTickerModule, LoginFormModule, OpportunitiesTickerModule, ProfileCardModule, ResetPasswordFormModule, RevenueAnalysisByStatesCardModule, RevenueAnalysisCardModule, RevenueCardModule, RevenueSnapshotByStatesCardModule, RevenueSnapshotCardModule, RevenueTotalTickerModule, SalesByRangeCardModule, SalesMapCardModule, SalesPerformanceCardModule, SalesRangeCardModule, StatusIndicatorModule } from '../components';
import { ContactNewFormModule } from '../components/library/contact-new-form/contact-new-form.component';
import { ContactPanelModule } from '../components/library/contact-panel/contact-panel.component';
import { DxBulletModule, DxButtonModule, DxCalendarModule, DxChartModule, DxDataGridModule, DxDateBoxModule, DxDropDownButtonModule, DxFileUploaderModule, DxFormModule, DxFunnelModule, DxLoadPanelModule, DxNumberBoxModule, DxPieChartModule, DxRangeSelectorModule, DxSchedulerModule, DxScrollViewModule, DxSelectBoxModule, DxSpeedDialActionModule, DxTabPanelModule, DxTabsModule, DxTextBoxModule, DxToolbarModule, DxTooltipModule, DxValidationGroupModule, DxVectorMapModule } from 'devextreme-angular';
import { SchedulerTooltipModule } from '../components/library/scheduler-tooltip/scheduler-tooltip.component';
import { AgendaModule } from '../components/utils/agenda/agenda.component';
import { RightSidePanelModule } from '../components/utils/right-side-panel/right-side-panel.component';
import { LeftSidePanelModule } from '../components/utils/left-side-panel/left-side-panel.component';
import { ApplyPipeModule } from '../pipes/apply.pipe';
import { CalendarListModule } from '../components/utils/calendar-list/calendar-list.component';
import { ContactCardsModule } from '../components/utils/contact-cards/contact-cards.component';
import { ContactFormModule } from '../components/library/contact-form/contact-form.component';
import { ToolbarAnalyticsModule } from '../components/utils/toolbar-analytics/toolbar-analytics.component';
import { CardAnalyticsModule } from '../components/library/card-analytics/card-analytics.component';
import { TaskListGanttModule } from '../components/library/task-list-gantt/task-list-gantt.component';
import { TaskListModule } from '../components/library/task-list-grid/task-list-grid.component';
import { TaskListKanbanModule } from '../components/library/task-list-kanban/task-list-kanban.component';
import { TaskFormModule } from '../components/library/task-form/task-form.component';
import { PhonePipeModule } from '../pipes/phone.pipe';



@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    DxButtonModule,
    DxDataGridModule,
    DxDropDownButtonModule,
    DxSelectBoxModule,
    DxTextBoxModule,
    ContactPanelModule,
    ContactNewFormModule,
    FormPopupModule,
    CardActivitiesModule,
    ContactStatusModule,
    ApplyPipeModule,
    DxCalendarModule,
    DxSchedulerModule,
    DxSpeedDialActionModule,
    DxTooltipModule,
    CalendarListModule,
    LeftSidePanelModule,
    RightSidePanelModule,
    AgendaModule,
    SchedulerTooltipModule,
    DxScrollViewModule,
    DxToolbarModule,
    ContactFormModule,
    ContactCardsModule,
    CardNotesModule,
    CardMessagesModule,
    DxLoadPanelModule,
    DxPieChartModule,
    DxChartModule,
    DxRangeSelectorModule,
    CardAnalyticsModule,
    ToolbarAnalyticsModule,
    SalesByRangeCardModule,
    SalesPerformanceCardModule,
    SalesRangeCardModule,
    DxBulletModule,
    DxVectorMapModule,
    RevenueAnalysisByStatesCardModule,
    SalesMapCardModule,
    RevenueSnapshotByStatesCardModule,
    DxFunnelModule,
    ConversionCardModule,
    RevenueAnalysisCardModule,
    RevenueCardModule,
    RevenueSnapshotCardModule,
    OpportunitiesTickerModule,
    RevenueTotalTickerModule,
    ConversionTickerModule,
    LeadsTickerModule,
    DxTabsModule,
    TaskFormModule,
    TaskListKanbanModule,
    TaskListModule,
    TaskListGanttModule,
    DxTabPanelModule,
    DxValidationGroupModule,
    StatusIndicatorModule,
    CardAuthModule,
    ResetPasswordFormModule,
    LoginFormModule,
    CreateAccountFormModule,
    DxDateBoxModule,
    DxFormModule,
    DxFileUploaderModule,
    DxNumberBoxModule,
    FormTextboxModule,
    FormPhotoModule,
    ProfileCardModule,
    ChangeProfilePasswordFormModule,
    PhonePipeModule,
  ],
  exports: [
    CommonModule,
    DxButtonModule,
    DxDataGridModule,
    DxDropDownButtonModule,
    DxSelectBoxModule,
    DxTextBoxModule,
    ContactPanelModule,
    ContactNewFormModule,
    FormPopupModule,
    CardActivitiesModule,
    ContactStatusModule,
    ApplyPipeModule,
    DxCalendarModule,
    DxSchedulerModule,
    DxSpeedDialActionModule,
    DxTooltipModule,
    CalendarListModule,
    LeftSidePanelModule,
    RightSidePanelModule,
    AgendaModule,
    SchedulerTooltipModule,
    DxScrollViewModule,
    DxToolbarModule,
    ContactFormModule,
    ContactCardsModule,
    CardNotesModule,
    CardMessagesModule,
    DxLoadPanelModule,
    DxPieChartModule,
    DxChartModule,
    DxRangeSelectorModule,
    CardAnalyticsModule,
    ToolbarAnalyticsModule,
    SalesByRangeCardModule,
    SalesPerformanceCardModule,
    SalesRangeCardModule,
    DxBulletModule,
    DxVectorMapModule,
    RevenueAnalysisByStatesCardModule,
    SalesMapCardModule,
    RevenueSnapshotByStatesCardModule,
    DxFunnelModule,
    ConversionCardModule,
    RevenueAnalysisCardModule,
    RevenueCardModule,
    RevenueSnapshotCardModule,
    OpportunitiesTickerModule,
    RevenueTotalTickerModule,
    ConversionTickerModule,
    LeadsTickerModule,
    DxTabsModule,
    TaskFormModule,
    TaskListKanbanModule,
    TaskListModule,
    TaskListGanttModule,
    DxTabPanelModule,
    DxValidationGroupModule,
    StatusIndicatorModule,
    CardAuthModule,
    ResetPasswordFormModule,
    LoginFormModule,
    CreateAccountFormModule,
    DxDateBoxModule,
    DxFormModule,
    DxFileUploaderModule,
    DxNumberBoxModule,
    FormTextboxModule,
    FormPhotoModule,
    ProfileCardModule,
    ChangeProfilePasswordFormModule,
    PhonePipeModule,
    DxDateBoxModule,
  ]
})
export class DevExtremeModule { }
